-- ============================================================================
-- AV DevLabs — Supabase (Postgres) Schema
-- ============================================================================
-- HOW TO USE:
-- 1. Go to your Supabase project → SQL Editor → New Query
-- 2. Paste this entire file and click "Run"
-- 3. This creates all 6 tables the app needs.
--
-- If you're migrating from the old Navkar Stationary schema, see the
-- MIGRATION NOTES at the bottom of this file before running this.
-- ============================================================================

-- 1. QUERIES (homepage "Submit a Query" form)
create table if not exists public.queries (
    id              bigint generated by default as identity primary key,
    name            text,
    gmail           text,
    query           text,
    status          text default 'Pending',
    admin_message   text default '',
    date            text,
    created_at      timestamptz default now()
);

-- 2. PLACE ORDERS (homepage "Place an Order" project-request form)
create table if not exists public.place_orders (
    id                      bigint generated by default as identity primary key,
    name                    text,
    contact_number          text,
    gmail                   text,
    category                text,
    special_instructions    text,
    status                  text default 'Pending',
    date                    text,
    created_at              timestamptz default now()
);

-- 3. TRASH (soft-deleted place orders)
create table if not exists public.trash (
    id                      bigint generated by default as identity primary key,
    original_order_id       bigint,
    name                    text,
    contact_number          text,
    gmail                   text,
    category                text,
    special_instructions    text,
    status                  text,
    date                    text,
    deleted_date            text,
    created_at              timestamptz default now()
);

-- 4. ANNOUNCEMENTS (circular homepage bubbles)
create table if not exists public.announcements (
    id          bigint generated by default as identity primary key,
    title       text,
    message     text,
    icon        text,
    color       text,
    date        text,
    created_at  timestamptz default now()
);

-- 5. PROJECTS (admin-curated portfolio -> shown as "Delivered Projects" on homepage)
create table if not exists public.projects (
    id              bigint generated by default as identity primary key,
    title           text,
    description     text,
    link            text,
    photo_urls      jsonb default '[]'::jsonb,  -- array of public Storage URLs
    date            text,
    created_at      timestamptz default now()
);

-- 6. REPORT LEADS (report-generation pipeline)
-- ----------------------------------------------------------------------------
-- Every time the Query or Place Order form is submitted, the app ALSO copies
-- just the report-relevant fields (name, gmail, category, source) into this
-- separate table. It is purely an additive side-copy - the original
-- `queries` / `place_orders` rows and workflow are never touched, read, or
-- altered by report generation.
--
-- De-duplication: `gmail` is UNIQUE. If a form is submitted with an email
-- that already exists here, that row is UPDATED in place (upsert) with the
-- latest name/category/source instead of creating a second row for the same
-- lead. A different email always creates a new, unique row.
create table if not exists public.report_leads (
    id          bigint generated by default as identity primary key,
    name        text,
    gmail       text unique,
    category    text,
    source      text,
    updated_at  timestamptz default now()
);

-- ============================================================================
-- Row Level Security
-- ----------------------------------------------------------------------------
-- The Flask backend talks to Supabase using the SERVICE ROLE key (kept secret
-- in your .env file, never sent to the browser). The service role key always
-- bypasses Row Level Security, so the app will keep working even with RLS on.
-- We enable RLS with no public policies here as a safety net, in case the
-- anon/public key is ever used accidentally.
-- ============================================================================
alter table public.queries enable row level security;
alter table public.place_orders enable row level security;
alter table public.trash enable row level security;
alter table public.announcements enable row level security;
alter table public.projects enable row level security;
alter table public.report_leads enable row level security;

-- ============================================================================
-- Storage bucket for Delivered Projects photos
-- ----------------------------------------------------------------------------
-- In the Supabase Dashboard: Storage -> New Bucket -> name it exactly
-- "project-photos" and mark it PUBLIC (so the homepage can display the
-- images directly via their public URL, no signed links required).
-- The Flask backend uploads to this bucket using the service_role key, which
-- bypasses bucket policies, so no additional storage policy is required for
-- the app itself to work.
-- ============================================================================

-- ============================================================================
-- MIGRATION NOTES (only relevant if you're upgrading an existing
-- Navkar Stationary Supabase project to AV DevLabs)
-- ----------------------------------------------------------------------------
-- The old project used different tables/columns (queries.whatsapp_number,
-- .department, .course, .semester, .subject; a shop "orders" table with
-- line_items/total; xerox_requests; products; report_students keyed by
-- whatsapp_number). None of that maps 1:1 onto the new AV DevLabs schema
-- above, so the safest path is:
--   1. Run the CREATE TABLE statements above as-is (they use
--      "if not exists", so they won't touch tables that already exist
--      under the OLD names like "orders" or "report_students").
--   2. If you want to keep old data for reference, rename the old tables
--      first (e.g. `alter table public.orders rename to public.orders_old;`)
--      so the new `place_orders` table is created fresh.
--   3. Old tables no longer used by the app (xerox_requests, products,
--      the old orders/report_students schema) can be dropped once you've
--      confirmed you don't need the historical data:
--         drop table if exists public.xerox_requests;
--         drop table if exists public.products;
-- ============================================================================
